### ISSUE TITLE
Use own @context file

### ISSUE THREAD

**Issue by MarieluiseOden** [Fiware/tutorials.Getting-Started#29]
Hi, 
I tried to replace the ngsi-cintext.jsonld file with my own context file. To do this, I replaced the file in the data-models folder. After starting the service, I tried to query this file at http://localhost:3000/data-models/ngsi-context.jsonld. But here I get the file from the FIWARE tutorial and not my own. It is not clear to me where this file comes from or how to include my own file. 
Maybe someone can help me to solve this problem.

**Comment by jason-fox** [comment]
The files in the `/data-models` directory of this tutorial are hosted by [Apache HTTPD](https://en.wikipedia.org/wiki/Apache_HTTP_Server). The service is defined [here](https://github.com/FIWARE/tutorials.Getting-Started/blob/NGSI-LD/docker-compose/common.yml#L20-#L33), so to access the files directly  you'll need to use port `3004` not port `3000` - http://localhost:3004/ngsi-context.jsonld

`localhost:3000` is referring to the tutorial app directly which used to serve copies of the `@context` as a fudge for historical reasons and simplicity. Usually for tutorials, there is no need to spin up  an extra container just to serve a single file - however the IoT devices  of the tutorial app will fail under load if this task is not delegated since the tutorial app is just a simple single threaded NodeJS app. The old (hopefully unused) files are found [here](https://github.com/FIWARE/tutorials.NGSI-LD/tree/master/app/public/data-models), and these were the ones you were accessing. Any references of reading the `@context` from `localhost:3000` are incorrect - you should check using `localhost:3004`.

Within the docker network the **Apache HTTPD** web server container uses the hostname `context`, so it can be accessed as follows:

```
Link: <http://context/json-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"
```

by other containers within the network (such as the context broker).
