### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by flemic** [Fiware/tutorials.Getting-Started#5]
Yo Jason, here are some initial comments:

- There should be an installation section: 
1) had to install virtualbox & docker-machine, in addition to docker itself 
2) had to create a default docker machine and connect my shell to the new machine
3) only then was able to pull mongo and orion

- I was not able to connect to orion ("curl: (7) Failed to connect to localhost port 1026: Connection refused"), had to change the command to "curl -X GET http://$(docker-machine ip default):1026/version"

- had to change all the following commands because the localhost or 0.0.0.0 didn't work

- the outputs of GET commands should be in a json format, but shown in the console as plain text. To get the output shown in the tutorial I had to use the following command:
"curl -X GET http://$(docker-machine ip default):1026/v2/entities/urn:ngsi-ld:Store:001?options=keyValues | python -m json.tool" (this also doesn't work for all GET commands, no idea why)

- my output was not UTF-8, but something like "Bornholmer Stra\u00dfe 65". I didn't bother to change it, but probably this should be mentioned. 

- perhaps the parameter/flag -X should be discussed

- for this command: "curl -X GET http://$(docker-machine ip default):1026/v2/entities?type=Store&georel=near;maxDistance:1500&geometry=point&coords=52.5162,13.3777" I get a confusing output:

[1] 3876
[2] 3877
[3] 3878
-bash: maxDistance:1500: command not found
[4] 3880
[2]   Done                    georel=near
[3]   Exit 127                maxDistance:1500
[4]+  Done                    geometry=point
Filips-MacBook-Air:~ flemic$ [{"id":"urn:ngsi-ld:Store:001","type":"Store","address":{"type":"PostalAddress","value":{"streetAddress":"Bornholmer Straße 65","addressRegion":"Berlin","addressLocality":"Prenzlauer Berg","postalCode":"10439"},"metadata":{}},"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3986,52.5547]},"metadata":{}},"name":{"type":"Text","value":"Bösebrücke Einkauf","metadata":{}}},{"id":"urn:ngsi-ld:Store:002","type":"Store","address":{"type":"PostalAddress","value":{"streetAddress":"Friedrichstraße 44","addressRegion":"Berlin","addressLocality":"Kreuzberg","postalCode":"10969"},"metadata":{}},"location":{"type":"geo:json","value":{"type":"Point","coordinates":[13.3903,52.5075]},"metadata":{}},"name":{"type":"Text","value":"Checkpoint Markt","metadata":{}}}]

Cheers!

**Comment by jason-fox** [comment]
1. Since the details of the developer's setup will vary, we can't cover all necessary steps for setting up Docker from scratch for all systems. I think we have to assume that the link to the Docker install should be enough. However what we can do is add a troubleshooting section when checking for the heartbeat to solve common issues (e.g. docker container not running, docker container on wrong port etc.)

2. Since this is not a cUrl tutorial we shouldn't discuss the usage of cUrl -X - the link at the head of the tutorial should be sufficient.

3. The responses have only been formatted for readability - it is not strictly necessary for the tutorial, and is a cUrl issue not a FIWARE issue. Finding a method for formatting a cUrl response can easily be found on [Stack Overflow](https://stackoverflow.com/questions/27238411/curl-output-to-display-in-the-readable-json-format-in-unix-shell-script)

4. The semi-colon `;` in the cUrl command is being interpreted as a break - the URL needs to be placed in quotes.
